"""empty message

Revision ID: 0ae00d7f1110
Revises: 679bfa6d8776
Create Date: 2017-07-27 10:15:50.766128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ae00d7f1110'
down_revision = '679bfa6d8776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketlist_items', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist_items', sa.Column('date_created', postgresql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
