"""empty message

Revision ID: 0c91e108febf
Revises: a9a9d15dd3bd
Create Date: 2017-07-13 19:10:14.841031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c91e108febf'
down_revision = 'a9a9d15dd3bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bucketlists_created_by_fkey', 'bucketlists', type_='foreignkey')
    op.drop_column('bucketlists', 'created_by')
    op.drop_constraint('users_public_id_key', 'users', type_='unique')
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_public_id_key', 'users', ['public_id'])
    op.add_column('bucketlists', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bucketlists_created_by_fkey', 'bucketlists', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
