"""empty message

Revision ID: 60663ff42dec
Revises: edba38bb406c
Create Date: 2017-07-27 10:48:34.207927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60663ff42dec'
down_revision = 'edba38bb406c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketlists', 'date_created')
    # ### end Alembic commands ###
