"""empty message

Revision ID: c6c823653c23
Revises: afd5e887bfae
Create Date: 2017-07-10 23:39:43.963964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c823653c23'
down_revision = 'afd5e887bfae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('bucketlists', 'fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('fullname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('bucketlists', 'name')
    # ### end Alembic commands ###
