"""empty message

Revision ID: c8e3c034f6f8
Revises: 0ae00d7f1110
Create Date: 2017-07-27 10:16:19.637105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e3c034f6f8'
down_revision = '0ae00d7f1110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist_items', sa.Column('date_created', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketlist_items', 'date_created')
    # ### end Alembic commands ###
