"""empty message

Revision ID: ecd08bb9b21e
Revises: f517ee94cb2e
Create Date: 2017-07-23 08:16:26.476929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd08bb9b21e'
down_revision = 'f517ee94cb2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist_items', sa.Column('complete_by', sa.DateTime(), nullable=True))
    op.add_column('bucketlist_items', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketlist_items', 'done')
    op.drop_column('bucketlist_items', 'complete_by')
    # ### end Alembic commands ###
