"""empty message

Revision ID: edba38bb406c
Revises: e6c70054da05
Create Date: 2017-07-27 10:46:33.016839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'edba38bb406c'
down_revision = 'e6c70054da05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketlists', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('date_created', postgresql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
